version: '3'
services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/ghibli
        depends_on:
            - redis
    redis:
        image: redis